"""Guarded live-Colab completion helpers for the A17 environment contract.

This module resolves metadata and exercises receipt plumbing. It never downloads model
weights, trains a model, runs inference, or evaluates a linguistic dataset.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib
import json
import platform
import re
import subprocess
import sys
import zipfile
from collections.abc import Mapping, Sequence
from datetime import datetime, timezone
from pathlib import Path, PurePosixPath
from typing import Any

from reproducibility import (
    ContractError,
    build_run_receipt,
    canonical_sha256,
    capture_accelerator,
    capture_repository,
    file_record,
    load_environment_lock,
    load_json_document,
    load_resolver_manifest,
    load_run_receipt,
    resolver_manifest_from_pip_report,
    sha256_file,
    stamp_document,
    validate_environment_lock,
    validate_preflight_report,
    verify_file_record,
    verify_resolver_evidence,
    write_json_document,
)

BACKBONE_RESOLUTION_FORMAT = "pyaegean-backbone-resolution/1"
DRY_RUN_OUTPUT_FORMAT = "pyaegean-a17-dry-run-output/1"
EVIDENCE_SUMMARY_FORMAT = "pyaegean-a17-evidence-summary/1"
REQUIRED_BACKBONE_FILES = (
    "config.json",
    "merges.txt",
    "special_tokens_map.json",
    "tokenizer.json",
    "tokenizer_config.json",
    "vocab.json",
)
A17_DIRECT_ROOTS = (
    "accelerate",
    "huggingface-hub",
    "numpy",
    "onnx",
    "onnxruntime-gpu",
    "safetensors",
    "tokenizers",
    "torch",
    "transformers",
)
EVIDENCE_FILENAMES = (
    "install-command.json",
    "pip-report.json",
    "pip-check.txt",
    "pip-freeze.txt",
    "nvidia-smi.txt",
    "resolver-manifest.json",
    "environment-candidate.json",
    "preflight.json",
    "environment-lock.json",
    "backbone-resolution.json",
    "dry-run-output.json",
    "run-receipt.json",
)
REVIEWED_EVIDENCE_FILENAMES = (
    "resolver-manifest.json",
    "preflight.json",
    "environment-lock.json",
    "backbone-resolution.json",
    "dry-run-output.json",
    "run-receipt.json",
)


def _canonical_text_file_record(path: Path, *, root: Path) -> dict[str, Any]:
    """Record committed text with Git's platform-independent LF representation."""

    record = file_record(path, root=root)
    content = path.read_bytes().replace(b"\r\n", b"\n")
    try:
        content.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise ContractError(f"A17 source input is not UTF-8 text: {record['path']}") from exc
    record["bytes"] = len(content)
    record["sha256"] = hashlib.sha256(content).hexdigest()
    return record


def _verify_canonical_text_file_record(
    record: Mapping[str, Any], *, root: Path
) -> None:
    path = root / str(record["path"])
    if _canonical_text_file_record(path, root=root) != record:
        raise ContractError(f"recorded source input differs: {record['path']}")


def _verify_a17_receipt_files(receipt: Mapping[str, Any], *, root: Path) -> None:
    """Verify generated bytes exactly and committed text independent of checkout EOLs."""

    verify_file_record(receipt["environment"]["lock"], root=root)
    _verify_canonical_text_file_record(receipt["run"]["config"], root=root)
    for record in receipt["datasets"]:
        _verify_canonical_text_file_record(record, root=root)
    for record in receipt["outputs"]:
        verify_file_record(record, root=root)


def _mapping(value: object, context: str) -> Mapping[str, Any]:
    if not isinstance(value, Mapping):
        raise ContractError(f"{context} must be an object")
    return value


def _exact_keys(value: Mapping[str, Any], expected: set[str], context: str) -> None:
    actual = set(value)
    if actual != expected:
        missing = sorted(expected - actual)
        extra = sorted(actual - expected)
        detail: list[str] = []
        if missing:
            detail.append("missing " + ", ".join(missing))
        if extra:
            detail.append("unknown " + ", ".join(extra))
        raise ContractError(f"{context} has invalid fields ({'; '.join(detail)})")


def _string(value: object, context: str) -> str:
    if not isinstance(value, str) or not value:
        raise ContractError(f"{context} must be a non-empty string")
    return value


def _hex(value: object, context: str, length: int) -> str:
    text = _string(value, context)
    if len(text) != length or any(character not in "0123456789abcdef" for character in text):
        raise ContractError(f"{context} must be {length} lowercase hexadecimal characters")
    return text


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")


def _git(repository_root: Path, *args: str) -> str:
    process = subprocess.run(
        ["git", *args],
        cwd=repository_root,
        check=False,
        capture_output=True,
        text=True,
        encoding="utf-8",
    )
    if process.returncode:
        raise ContractError(process.stderr.strip() or process.stdout.strip() or "git failed")
    return process.stdout.strip()


def _require_tracked(path: Path, *, repository_root: Path, context: str) -> None:
    try:
        relative = path.resolve().relative_to(repository_root.resolve()).as_posix()
    except ValueError as exc:
        raise ContractError(f"{context} must be inside the repository") from exc
    _git(repository_root, "ls-files", "--error-unmatch", "--", relative)


def _require_ignored_untracked(path: Path, *, repository_root: Path, context: str) -> None:
    try:
        relative = path.resolve().relative_to(repository_root.resolve()).as_posix()
    except ValueError as exc:
        raise ContractError(f"{context} must be inside the repository") from exc
    tracked = subprocess.run(
        ["git", "ls-files", "--error-unmatch", "--", relative],
        cwd=repository_root,
        check=False,
        capture_output=True,
        text=True,
        encoding="utf-8",
    )
    if tracked.returncode == 0:
        raise ContractError(f"{context} must be an ignored, untracked evidence path")
    ignored = subprocess.run(
        ["git", "check-ignore", "-q", "--", relative],
        cwd=repository_root,
        check=False,
    )
    if ignored.returncode != 0:
        raise ContractError(f"{context} must be ignored so evidence capture keeps Git clean")


def validate_backbone_resolution(
    proof: Mapping[str, Any], *, environment_lock: Mapping[str, Any] | None = None
) -> None:
    """Validate one content-addressed, metadata-only immutable-backbone proof."""

    proof = _mapping(proof, "backbone resolution")
    _exact_keys(
        proof,
        {
            "format",
            "repository",
            "requested_revision",
            "resolved_revision",
            "tokenizer_revision",
            "required_files",
            "available_files",
            "resolution_sha256",
        },
        "backbone resolution",
    )
    if proof["format"] != BACKBONE_RESOLUTION_FORMAT:
        raise ContractError(f"unsupported backbone resolution format: {proof['format']!r}")
    _string(proof["repository"], "backbone resolution.repository")
    for field in ("requested_revision", "resolved_revision", "tokenizer_revision"):
        _hex(proof[field], f"backbone resolution.{field}", 40)
    if proof["requested_revision"] != proof["resolved_revision"]:
        raise ContractError("backbone API resolved a different revision")
    if proof["tokenizer_revision"] != proof["resolved_revision"]:
        raise ContractError("tokenizer revision differs from the resolved backbone revision")
    for field in ("required_files", "available_files"):
        values = proof[field]
        if not isinstance(values, list) or not values:
            raise ContractError(f"backbone resolution.{field} must be a non-empty array")
        if any(not isinstance(item, str) or not item for item in values):
            raise ContractError(f"backbone resolution.{field} contains an invalid filename")
        if values != sorted(set(values)):
            raise ContractError(f"backbone resolution.{field} must be unique and sorted")
    if proof["required_files"] != list(REQUIRED_BACKBONE_FILES):
        raise ContractError("backbone resolution required-file contract differs from A17")
    missing = sorted(set(proof["required_files"]) - set(proof["available_files"]))
    if missing:
        raise ContractError("backbone revision lacks required files: " + ", ".join(missing))
    recorded = _hex(proof["resolution_sha256"], "backbone resolution.resolution_sha256", 64)
    actual = canonical_sha256(
        {key: value for key, value in proof.items() if key != "resolution_sha256"}
    )
    if recorded != actual:
        raise ContractError(
            f"backbone resolution digest mismatch: expected {recorded}, recomputed {actual}"
        )
    if environment_lock is not None:
        validate_environment_lock(environment_lock)
        backbone = environment_lock["backbone"]
        if proof["repository"] != backbone["repository"]:
            raise ContractError("backbone resolution repository differs from environment lock")
        if proof["resolved_revision"] != backbone["revision"]:
            raise ContractError("backbone resolution revision differs from environment lock")
        if proof["tokenizer_revision"] != backbone["tokenizer_revision"]:
            raise ContractError("tokenizer resolution differs from environment lock")


def load_backbone_resolution(
    path: Path | str, *, environment_lock: Mapping[str, Any] | None = None
) -> dict[str, Any]:
    proof = load_json_document(path)
    validate_backbone_resolution(proof, environment_lock=environment_lock)
    return proof


def resolve_backbone_metadata(lock: Mapping[str, Any]) -> dict[str, Any]:
    """Resolve the frozen Hugging Face commit through metadata only."""

    validate_environment_lock(lock)
    backbone = lock["backbone"]
    try:
        huggingface_hub = importlib.import_module("huggingface_hub")
        info = huggingface_hub.HfApi().model_info(
            backbone["repository"],
            revision=backbone["revision"],
            files_metadata=False,
            timeout=30.0,
        )
    except Exception as exc:
        raise ContractError(f"cannot resolve immutable backbone metadata: {exc}") from exc
    available = sorted(
        {
            _string(getattr(sibling, "rfilename", None), "backbone sibling filename")
            for sibling in getattr(info, "siblings", ())
        }
    )
    proof = stamp_document(
        {
            "format": BACKBONE_RESOLUTION_FORMAT,
            "repository": backbone["repository"],
            "requested_revision": backbone["revision"],
            "resolved_revision": _string(getattr(info, "sha", None), "resolved backbone SHA"),
            "tokenizer_revision": backbone["tokenizer_revision"],
            "required_files": list(REQUIRED_BACKBONE_FILES),
            "available_files": available,
        },
        "resolution_sha256",
    )
    validate_backbone_resolution(proof, environment_lock=lock)
    return proof


def _cpu_name() -> str:
    name = platform.processor().strip()
    if name:
        return name
    try:
        for line in Path("/proc/cpuinfo").read_text(encoding="utf-8").splitlines():
            if line.lower().startswith("model name") and ":" in line:
                candidate = line.split(":", 1)[1].strip()
                if candidate:
                    return candidate
    except OSError:
        pass
    return "unknown CPU"


def capture_run_hardware() -> dict[str, Any]:
    """Capture the receipt's single-allocation hardware facts without model execution."""

    accelerator = capture_accelerator()
    torch = importlib.import_module("torch")
    gpu_count = int(torch.cuda.device_count())
    if gpu_count < 1:
        raise ContractError("torch reported no visible GPU for the A17 dry run")
    names = [str(torch.cuda.get_device_name(index)) for index in range(gpu_count)]
    if len(set(names)) != 1:
        raise ContractError("A17 dry-run receipt requires a homogeneous visible GPU allocation")
    capabilities = [tuple(torch.cuda.get_device_capability(index)) for index in range(gpu_count)]
    if len(set(capabilities)) != 1:
        raise ContractError("visible GPUs report different compute capabilities")
    memories = [int(torch.cuda.get_device_properties(index).total_memory) for index in range(gpu_count)]
    if len(set(memories)) != 1 or memories[0] < 1:
        raise ContractError("visible GPUs report invalid or different memory capacities")
    capability = capabilities[0]
    return {
        "platform": platform.platform(),
        "machine": platform.machine(),
        "cpu": _cpu_name(),
        "gpu": names[0],
        "gpu_count": gpu_count,
        "gpu_memory_bytes": memories[0],
        "driver_version": accelerator["driver_version"],
        "cuda_runtime_version": accelerator["cuda_runtime_version"],
        "torch_cuda_version": accelerator["torch_cuda_version"],
        "cudnn_version": accelerator["cudnn_version"],
        "compute_capability": f"{capability[0]}.{capability[1]}",
        "precision": accelerator["precision"],
    }


def _load_fixture(path: Path) -> list[Mapping[str, Any]]:
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except OSError as exc:
        raise ContractError(f"cannot read A17 fixture {path}: {exc}") from exc
    records: list[Mapping[str, Any]] = []
    for index, line in enumerate(lines, start=1):
        if not line.strip():
            continue
        try:
            value = json.loads(line)
        except json.JSONDecodeError as exc:
            raise ContractError(f"invalid A17 fixture JSON on line {index}: {exc}") from exc
        records.append(_mapping(value, f"A17 fixture line {index}"))
    if not records:
        raise ContractError("A17 dry-run fixture must contain at least one record")
    return records


def run_dry_receipt(
    *,
    lock_path: Path,
    preflight_path: Path,
    backbone_path: Path,
    config_path: Path,
    dataset_path: Path,
    output_path: Path,
    receipt_path: Path,
    repository_root: Path,
) -> dict[str, Any]:
    """Exercise and verify the completed-run path with a deterministic tiny fixture."""

    started = _utc_now()
    lock = load_environment_lock(lock_path)
    validate_environment_lock(lock, require_validated=True)
    verify_resolver_evidence(lock, root=repository_root)
    preflight = load_json_document(preflight_path)
    validate_preflight_report(preflight, environment_lock=lock)
    if not preflight["ok"]:
        raise ContractError("A17 dry run requires a successful preflight")
    backbone = load_backbone_resolution(backbone_path, environment_lock=lock)
    config = load_json_document(config_path)
    _exact_keys(
        config,
        {
            "format",
            "purpose",
            "seed",
            "training_performed",
            "inference_performed",
            "evaluation_performed",
        },
        "A17 dry-run config",
    )
    if config["format"] != "pyaegean-a17-dry-run-config/1":
        raise ContractError("unsupported A17 dry-run config format")
    if config["purpose"] != "environment-and-receipt-contract-smoke-test":
        raise ContractError("A17 dry-run config has an unexpected purpose")
    for field in ("training_performed", "inference_performed", "evaluation_performed"):
        if config[field] is not False:
            raise ContractError(f"A17 dry-run config.{field} must be false")
    seed = config.get("seed")
    if not isinstance(seed, int) or isinstance(seed, bool) or seed < 0:
        raise ContractError("A17 dry-run config.seed must be a non-negative integer")
    records = _load_fixture(dataset_path)
    _require_tracked(config_path, repository_root=repository_root, context="A17 dry-run config")
    _require_tracked(dataset_path, repository_root=repository_root, context="A17 fixture")
    for path, context in (
        (lock_path, "validated environment lock"),
        (preflight_path, "preflight receipt"),
        (backbone_path, "backbone proof"),
        (output_path, "dry-run output"),
        (receipt_path, "dry-run receipt"),
    ):
        _require_ignored_untracked(path, repository_root=repository_root, context=context)
    repository = capture_repository(repository_root)
    if repository["dirty"]:
        raise ContractError("A17 dry run requires a clean repository")
    if repository != preflight["observed"]["repository"]:
        raise ContractError("A17 dry run and preflight must observe the same clean source commit")
    dry_output = stamp_document(
        {
            "format": DRY_RUN_OUTPUT_FORMAT,
            "purpose": "environment-and-receipt-contract-smoke-test",
            "training_performed": False,
            "inference_performed": False,
            "evaluation_performed": False,
            "fixture_records": len(records),
            "fixture_payload_sha256": canonical_sha256(records),
            "config_sha256": _canonical_text_file_record(
                config_path, root=repository_root
            )["sha256"],
            "environment_definition_sha256": lock["environment_definition_sha256"],
            "preflight_sha256": preflight["preflight_sha256"],
            "backbone_resolution_sha256": backbone["resolution_sha256"],
            "repository_commit": repository["commit"],
            "seed": seed,
        },
        "output_sha256",
    )
    write_json_document(output_path, dry_output)
    if capture_repository(repository_root) != repository:
        raise ContractError("writing ignored A17 evidence unexpectedly changed repository state")
    finished = _utc_now()
    receipt = build_run_receipt(
        run={
            "id": f"a17-environment-dry-run-{repository['commit'][:12]}",
            "status": "completed",
            "started_utc": started,
            "finished_utc": finished,
            "command": [
                "python",
                "training/a17_colab.py",
                "dry-run",
                "--lock",
                lock_path.relative_to(repository_root).as_posix(),
            ],
            "config": _canonical_text_file_record(config_path, root=repository_root),
            "seed": seed,
        },
        repository=repository,
        environment={
            "lock": file_record(lock_path, root=repository_root),
            "lock_sha256": lock["lock_sha256"],
            "dependency_scope": lock["dependencies"]["scope"],
            "dependency_inventory_complete": lock["dependencies"]["complete"],
            "preflight_receipt_sha256": lock["verification"]["preflight_receipt_sha256"],
            "packages": lock["dependencies"]["packages"],
        },
        backbone=lock["backbone"],
        corpora=[
            {
                "name": "pyaegean-a17-reproducibility-fixture",
                "repository": repository["url"],
                "commit": repository["commit"],
            }
        ],
        datasets=[_canonical_text_file_record(dataset_path, root=repository_root)],
        outputs=sorted(
            (
                file_record(output_path, root=repository_root),
                file_record(backbone_path, root=repository_root),
            ),
            key=lambda record: record["path"],
        ),
        hardware=capture_run_hardware(),
        environment_lock=lock,
    )
    write_json_document(receipt_path, receipt)
    loaded = load_run_receipt(receipt_path, environment_lock=lock)
    _verify_a17_receipt_files(loaded, root=repository_root)
    return receipt


def verify_evidence(evidence_dir: Path, *, repository_root: Path) -> dict[str, Any]:
    """Re-verify the complete live archive and write its content-addressed summary."""

    paths = {name: evidence_dir / name for name in EVIDENCE_FILENAMES}
    missing = [name for name, path in paths.items() if not path.is_file()]
    if missing:
        raise ContractError("A17 evidence is incomplete: " + ", ".join(missing))
    install = load_json_document(paths["install-command.json"])
    _exact_keys(
        install,
        {"format", "operation_count", "argv", "requirements"},
        "A17 install command",
    )
    if install["format"] != "pyaegean-a17-install-command/1":
        raise ContractError("unsupported A17 install-command evidence format")
    if (
        isinstance(install["operation_count"], bool)
        or not isinstance(install["operation_count"], int)
        or install["operation_count"] != 1
    ):
        raise ContractError("A17 dependencies must be installed in one resolver operation")
    argv = install["argv"]
    if not isinstance(argv, list) or any(not isinstance(item, str) or not item for item in argv):
        raise ContractError("A17 install-command argv must be a non-empty string array")
    if PurePosixPath(argv[0]) != PurePosixPath("/content/pyaegean-a17-venv/bin/python"):
        raise ContractError("A17 install command did not use the fixed external Colab venv")
    expected_requirements_path = (repository_root / "training" / "a17-requirements.txt").resolve()
    expected_argv = [
        "/content/pyaegean-a17-venv/bin/python",
        "-m",
        "pip",
        "install",
        "--no-cache-dir",
        "--index-url",
        "https://pypi.org/simple",
        "--extra-index-url",
        "https://download.pytorch.org/whl/cu128",
        "--report",
        "/content/pyaegean-a17/training/results/a17-environment/pip-report.json",
        "--requirement",
        "/content/pyaegean-a17/training/a17-requirements.txt",
    ]
    if len(argv) != len(expected_argv) or any(
        PurePosixPath(item) != PurePosixPath(expected)
        if index in {0, 10, 12}
        else item != expected
        for index, (item, expected) in enumerate(zip(argv, expected_argv, strict=True))
    ):
        raise ContractError("A17 install command differs from the single frozen resolver operation")
    requirements_record = _canonical_text_file_record(
        expected_requirements_path, root=repository_root
    )
    if install["requirements"] != requirements_record:
        raise ContractError("A17 install command does not bind the committed requirements file")
    pip_report = load_json_document(paths["pip-report.json"])
    manifest = load_resolver_manifest(paths["resolver-manifest.json"])
    if resolver_manifest_from_pip_report(pip_report) != manifest:
        raise ContractError("normalized resolver manifest differs from the retained pip report")
    if manifest["direct_roots"] != list(A17_DIRECT_ROOTS):
        raise ContractError("resolver report does not contain the nine frozen A17 direct roots")
    candidate = load_environment_lock(paths["environment-candidate.json"])
    if candidate["verification"]["state"] != "captured-candidate":
        raise ContractError("A17 candidate lock is not a captured candidate")
    lock = load_environment_lock(paths["environment-lock.json"])
    validate_environment_lock(lock, require_validated=True)
    verify_resolver_evidence(lock, root=repository_root)
    expected_resolver_file = file_record(paths["resolver-manifest.json"], root=repository_root)
    if lock["dependencies"]["resolver_evidence"]["file"] != expected_resolver_file:
        raise ContractError("validated lock does not bind the archived resolver manifest path")
    if candidate["dependencies"]["resolver_evidence"]["file"] != expected_resolver_file:
        raise ContractError("captured candidate does not bind the archived resolver manifest path")
    if candidate["environment_definition_sha256"] != lock["environment_definition_sha256"]:
        raise ContractError("promotion changed the captured environment definition")
    preflight = load_json_document(paths["preflight.json"])
    validate_preflight_report(preflight, environment_lock=lock)
    if not preflight["ok"]:
        raise ContractError("A17 preflight evidence did not pass")
    proof = load_backbone_resolution(paths["backbone-resolution.json"], environment_lock=lock)
    receipt = load_run_receipt(paths["run-receipt.json"], environment_lock=lock)
    _verify_a17_receipt_files(receipt, root=repository_root)
    expected_lock_file = file_record(paths["environment-lock.json"], root=repository_root)
    if receipt["environment"]["lock"] != expected_lock_file:
        raise ContractError("dry-run receipt does not bind the archived validated lock")
    if receipt["repository"] != preflight["observed"]["repository"]:
        raise ContractError("dry-run receipt and preflight observed different source states")
    pip_check = paths["pip-check.txt"].read_text(encoding="utf-8").strip()
    if "No broken requirements found." not in pip_check:
        raise ContractError("retained pip check did not report a sound environment")
    if not paths["pip-freeze.txt"].read_text(encoding="utf-8").strip():
        raise ContractError("retained pip freeze is empty")
    nvidia_smi = paths["nvidia-smi.txt"].read_text(encoding="utf-8").strip()
    if "NVIDIA-SMI" not in nvidia_smi or receipt["hardware"]["gpu"] not in nvidia_smi:
        raise ContractError("retained nvidia-smi output does not identify the captured GPU")
    frozen: dict[str, str] = {}
    for line in paths["pip-freeze.txt"].read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if "==" not in stripped:
            raise ContractError(f"unsupported pip-freeze entry: {stripped}")
        raw_name, version = stripped.split("==", 1)
        name = re.sub(r"[-_.]+", "-", raw_name).lower()
        # pip was bootstrapped separately before the one frozen resolver
        # operation. setuptools/wheel count when that operation installs them.
        if name != "pip":
            frozen[name] = version
    manifest_versions = {
        package["name"]: package["version"] for package in manifest["resolved_packages"]
    }
    if frozen != manifest_versions:
        only_frozen = sorted(set(frozen) - set(manifest_versions))
        only_manifest = sorted(set(manifest_versions) - set(frozen))
        changed = sorted(
            name
            for name in set(frozen) & set(manifest_versions)
            if frozen[name] != manifest_versions[name]
        )
        raise ContractError(
            "pip freeze differs from the normalized resolver closure "
            f"(freeze-only={only_frozen}, manifest-only={only_manifest}, "
            f"version-mismatch={changed})"
        )
    expected_config = "training/a17-dry-run-config.json"
    expected_dataset = "training/fixtures/a17-dry-run.jsonl"
    if receipt["run"]["config"]["path"] != expected_config:
        raise ContractError("dry-run receipt does not bind the committed A17 config")
    if [record["path"] for record in receipt["datasets"]] != [expected_dataset]:
        raise ContractError("dry-run receipt does not bind the committed A17 fixture")
    expected_outputs = {
        paths["dry-run-output.json"].relative_to(repository_root).as_posix(),
        paths["backbone-resolution.json"].relative_to(repository_root).as_posix(),
    }
    if {record["path"] for record in receipt["outputs"]} != expected_outputs:
        raise ContractError("dry-run receipt has an unexpected output set")
    artifacts = [file_record(paths[name], root=repository_root) for name in EVIDENCE_FILENAMES]
    summary = stamp_document(
        {
            "format": EVIDENCE_SUMMARY_FORMAT,
            "source_repository": receipt["repository"]["url"],
            "source_commit": receipt["repository"]["commit"],
            "hardware": dict(receipt["hardware"]),
            "environment_definition_sha256": lock["environment_definition_sha256"],
            "lock_sha256": lock["lock_sha256"],
            "preflight_sha256": preflight["preflight_sha256"],
            "resolver_manifest_sha256": manifest["manifest_sha256"],
            "backbone_resolution_sha256": proof["resolution_sha256"],
            "run_receipt_sha256": receipt["receipt_sha256"],
            "artifacts": artifacts,
        },
        "summary_sha256",
    )
    write_json_document(evidence_dir / "evidence-summary.json", summary)
    return summary


def bundle_evidence(
    evidence_dir: Path, *, repository_root: Path, output: Path
) -> dict[str, Any]:
    """Verify and archive only the declared A17 evidence files."""

    summary = verify_evidence(evidence_dir, repository_root=repository_root)
    output.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for name in (*EVIDENCE_FILENAMES, "evidence-summary.json"):
            path = evidence_dir / name
            info = zipfile.ZipInfo(path.relative_to(repository_root).as_posix())
            info.date_time = (1980, 1, 1, 0, 0, 0)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o100644 << 16
            archive.writestr(info, path.read_bytes())
    return {
        "ok": True,
        "archive": output.as_posix(),
        "archive_bytes": output.stat().st_size,
        "archive_sha256": sha256_file(output),
        "summary_sha256": summary["summary_sha256"],
    }


def write_reviewed_evidence_summary(
    evidence_dir: Path, *, repository_root: Path, output: Path
) -> dict[str, Any]:
    """Verify raw evidence, then summarize only the normalized publishable records."""

    full_summary = verify_evidence(evidence_dir, repository_root=repository_root)
    reviewed = stamp_document(
        {
            key: value
            for key, value in full_summary.items()
            if key not in {"artifacts", "summary_sha256"}
        }
        | {
            "artifacts": [
                file_record(evidence_dir / name, root=repository_root)
                for name in REVIEWED_EVIDENCE_FILENAMES
            ]
        },
        "summary_sha256",
    )
    write_json_document(output, reviewed)
    return reviewed


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Guarded live-Colab helpers for the pyaegean A17 environment checkpoint."
    )
    commands = parser.add_subparsers(dest="command", required=True)
    resolve = commands.add_parser(
        "resolve-backbone", help="verify the immutable Hugging Face revision through metadata only"
    )
    resolve.add_argument("--lock", type=Path, required=True)
    resolve.add_argument("--output", type=Path, required=True)
    dry = commands.add_parser(
        "dry-run", help="exercise the completed-run receipt contract without model execution"
    )
    dry.add_argument("--lock", type=Path, required=True)
    dry.add_argument("--preflight", type=Path, required=True)
    dry.add_argument("--backbone-resolution", type=Path, required=True)
    dry.add_argument("--config", type=Path, required=True)
    dry.add_argument("--dataset", type=Path, required=True)
    dry.add_argument("--output", type=Path, required=True)
    dry.add_argument("--receipt", type=Path, required=True)
    dry.add_argument("--repository-root", type=Path, required=True)
    verify = commands.add_parser("verify", help="re-verify a returned A17 evidence directory")
    verify.add_argument("--evidence-dir", type=Path, required=True)
    verify.add_argument("--repository-root", type=Path, required=True)
    bundle = commands.add_parser("bundle", help="verify and zip the declared A17 evidence files")
    bundle.add_argument("--evidence-dir", type=Path, required=True)
    bundle.add_argument("--repository-root", type=Path, required=True)
    bundle.add_argument("--output", type=Path, required=True)
    reviewed = commands.add_parser(
        "reviewed-summary", help="write a summary containing only normalized reviewed evidence"
    )
    reviewed.add_argument("--evidence-dir", type=Path, required=True)
    reviewed.add_argument("--repository-root", type=Path, required=True)
    reviewed.add_argument("--output", type=Path, required=True)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    try:
        if args.command == "resolve-backbone":
            lock = load_environment_lock(args.lock)
            proof = resolve_backbone_metadata(lock)
            write_json_document(args.output, proof)
            result = {
                "ok": True,
                "output": args.output.as_posix(),
                "resolved_revision": proof["resolved_revision"],
                "resolution_sha256": proof["resolution_sha256"],
            }
        elif args.command == "dry-run":
            receipt = run_dry_receipt(
                lock_path=args.lock,
                preflight_path=args.preflight,
                backbone_path=args.backbone_resolution,
                config_path=args.config,
                dataset_path=args.dataset,
                output_path=args.output,
                receipt_path=args.receipt,
                repository_root=args.repository_root,
            )
            result = {
                "ok": True,
                "receipt": args.receipt.as_posix(),
                "receipt_sha256": receipt["receipt_sha256"],
            }
        elif args.command == "verify":
            summary = verify_evidence(args.evidence_dir, repository_root=args.repository_root)
            result = {
                "ok": True,
                "summary": (args.evidence_dir / "evidence-summary.json").as_posix(),
                "summary_sha256": summary["summary_sha256"],
            }
        elif args.command == "bundle":
            result = bundle_evidence(
                args.evidence_dir,
                repository_root=args.repository_root,
                output=args.output,
            )
        else:
            summary = write_reviewed_evidence_summary(
                args.evidence_dir,
                repository_root=args.repository_root,
                output=args.output,
            )
            result = {
                "ok": True,
                "summary": args.output.as_posix(),
                "summary_sha256": summary["summary_sha256"],
            }
    except (ContractError, OSError) as exc:
        print(json.dumps({"ok": False, "error": str(exc)}, sort_keys=True), file=sys.stderr)
        return 1
    print(json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
